version: "3.8"

services:
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4202
      - POSTGRES_DB=CRUD
    networks:
      - backend

  # spring:
  #   container_name: spring
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/CRUD
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=4202
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #   depends_on:
  #     - db
  #   networks:
  #     - backend
  #     - frontend

  react:
    container_name: react
    build: ./frontend
    ports:
      - "5173:5173"
    restart: always
    network_mode: host

networks:
  frontend:
  backend:
