services:
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4202
      - POSTGRES_DB=CRUD
    volumes:
      - db-data:/var/lib/postgresql/data

  backend-app:
    container_name: backend-app
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/CRUD
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4202
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  react:
    container_name: react
    build: ./frontend
    ports:
      - "5174:5174"  # Ensure you map port 5173 for React app
    depends_on:
      - backend-app
    restart: always

volumes:
  db-data:
